[skip]
apps = ["steam"]

[launch]
# Map app_id to the actual command to spawn
"chromium-example.com__-Default" = "example-web-app"
"org.gnome.Nautilus" = "nautilus"
"app.zen_browser.zen" = "zen-browser"
"code" = "code"